[package]
name = "rpc"
version = "0.1.0"
authors = ["Hamza Tokuchi <h@mza.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
